[Feature]: uniform input and output format for transforms
alibaba/EasyCV pull request #6
Opened 2022-04-06 12:04 UTC by Cathy0908

2022-04-06 12:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/EasyCV?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/EasyCV?pullRequest=6) before we can accept your contribution.<br/><hr/>**jiangnana.jnn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/EasyCV?pullRequest=6) it.</sub>

2022-04-06 12:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/EasyCV?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/EasyCV?pullRequest=6) before we can accept your contribution.<br/><hr/>**jiangnana.jnn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/EasyCV?pullRequest=6) it.</sub>

2022-04-06 14:24 UTC, wenmengzhou commented on configs/release_test/selfsup/jpg/tranformer_mocov2.py
> +    dict(type='Collect', keys=['img'])
configs  in release_test can be removed

2022-04-06 14:53 UTC, wenmengzhou requested changes
1. configs in release_test can be remove

2. `has_label` attr should be deal with carefully

2022-04-07 06:31 UTC, Cathy0908 commented on configs/release_test/selfsup/jpg/tranformer_mocov2.py
> +    dict(type='Collect', keys=['img'])
removed

2022-04-07 07:02 UTC, tuofeilunhifi approved these changes

2022-04-07 07:03 UTC, merged